//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Desktop_NT20_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Account : INotifyPropertyChanged
    {
        public string accountId { get; set; }
        public string name { get; set; }
        public Nullable<int> balance { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string email { get; set; }
        public string PIN { get; set; }

        public void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName)); 
        }

        public event PropertyChangedEventHandler PropertyChanged;
    }
}
