//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Desktop_NT20_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department : ObservableObject
    {
        #region Attribute
        private string departmentId;
        private string name;


        #endregion
        public Department(string departmentId, string name)
        {
            this.departmentId = departmentId;
            this.name = name;
        }

        public string DepartmentId
        {
            get { return departmentId; }
            set { departmentId = value; OnPropertyChanged("DepartmentId");  }
        }


        public string Name
        {
            get { return name; }
            set { name = value; OnPropertyChanged("Name"); }
        }
    }
}
