//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Desktop_NT20_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee : ObservableObject
    {
        #region attribute
        private string employeeId;
        private string name;
        private DateTime dob;
        private string email;
        private string password;
        private Department department;
        #endregion

        public Employee() { }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee(string employeeId, string name, DateTime dob, string email, string password, Department department)
        {
            this.employeeId = employeeId;
            this.name = name;
            this.dob = dob;
            this.email = email;
            this.password = password;
            this.department = department;
            this.RequestExpenses = new HashSet<RequestExpense>();
            this.SalaryRaiseRequests = new HashSet<SalaryRaiseRequest>();
            this.Transactions = new HashSet<Transaction>();
            this.ViolationReports = new HashSet<ViolationReport>();
        }

        public Department Department
        {
            get { return department; }
            set { department = value; OnPropertyChanged("Department"); }
        }

        #region properties 
        public string EmployeeId
        {
            get { return employeeId; }
            set { employeeId = value; OnPropertyChanged("EmployeeId"); }
        }


        public string Name
        {
            get { return name; }
            set { name = value; OnPropertyChanged("Name"); }
        }


        public DateTime Dob
        {
            get { return dob; }
            set { dob = value; OnPropertyChanged("Dob"); }
        }

        public string Email
        {
            get { return email; }
            set { email = value; OnPropertyChanged("Email"); }
        }


        public string Password
        {
            get { return password; }
            set { password = value; OnPropertyChanged("Password"); }
        }

        #endregion

        public virtual ICollection<RequestExpense> RequestExpenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalaryRaiseRequest> SalaryRaiseRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViolationReport> ViolationReports { get; set; }
    }
}
