//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Desktop_NT20_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCCredit
    {
        public string HOCId { get; set; }
        public string AccountId { get; set; }
        public string CompanyId { get; set; }
        public decimal HousePrice { get; set; }
        public decimal InitialDeposit { get; set; }
        public int CreditPeriod { get; set; }
        public System.DateTime StartDate { get; set; }
        public decimal GrossIncome { get; set; }
        public bool IsApproved { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual HouseCompany HouseCompany { get; set; }
        public virtual HOCCreditDetail HOCCreditDetail { get; set; }
    }
}
