//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Desktop_NT20_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IndividualAccount()
        {
            this.StudentAccounts = new HashSet<StudentAccount>();
        }
    
        public string AccountId { get; set; }
        public string LevelName { get; set; }
        public decimal InterestRate { get; set; }
        public decimal InitialDeposit { get; set; }
        public decimal MinimumSaving { get; set; }
        public decimal AdminFee { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual BusinessAccount BusinessAccount { get; set; }
        public virtual Level Level { get; set; }
        public virtual RegularAccount RegularAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAccount> StudentAccounts { get; set; }
    }
}
