//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Desktop_NT20_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.MaintenanceReports = new HashSet<MaintenanceReport>();
        }
    
        public string ItemId { get; set; }
        public string Name { get; set; }
        public string ItemTypeId { get; set; }
        public string DepartmentId { get; set; }
        public decimal Value { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ItemType ItemType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceReport> MaintenanceReports { get; set; }
    }
}
