//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Desktop_NT20_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public string LoanId { get; set; }
        public string AccountId { get; set; }
        public string LoanTypeName { get; set; }
        public decimal LoanAmount { get; set; }
        public string GuranteeDocument { get; set; }
        public string LoanReason { get; set; }
        public bool IsApproved { get; set; }
        public bool IsPaid { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.DateTime PaidDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual LoanType LoanType { get; set; }
    }
}
