//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Desktop_NT20_2.Models
{
    using System;
    using System.Collections.Generic;

    public partial class MaintenanceReport : ObservableObject
    {
        public string ReportId { get; set; }
        public string EmployeeId { get; set; }
        public string ItemId { get; set; }
        public System.DateTime ReportDate { get; set; }
        public bool Status { get; set; }
        public string Description { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual Item Item { get; set; }
        public virtual MaintenanceSchedule MaintenanceSchedule { get; set; }

    }
}
