//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Desktop_NT20_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegularAccount : IndividualAccount
    {
        private SavingAccount savingAccount;
        private DepositAccount depositAccount;

        public SavingAccount SavingAccount
        {
            get { return savingAccount; }
            set { savingAccount = value; OnPropertyChanged("SavingAccount"); }
        }

        public DepositAccount DepositAccount
        {
            get { return depositAccount; }
            set { depositAccount = value; OnPropertyChanged("DepositAccount"); }
        }

        public RegularAccount(string accountId, string name, double balance, DateTime dob, string address, string email, 
            string pin, Level level, double interestRate, double initialDeposit, double minimumSaving, double adminFee) 
            : base(accountId, name, balance, dob, address, email, pin, level, interestRate, initialDeposit, minimumSaving, adminFee)
        {
            AccountId = accountId;
            Name = name;
            Balance = balance;
            Dob = dob;
            Address = address;
            Email = email;
            Pin = pin;
            CreatedAt = DateTime.Now;
            LevelAtt = level;
            InterestRate = interestRate;
            InitialDeposit = initialDeposit;
            MinimumSaving = minimumSaving;
            AdminFee = adminFee;
        }
    }
}
