//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Desktop_NT20_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string TransactionId { get; set; }
        public string AccountId { get; set; }
        public string RelatedAccountId { get; set; }
        public string EmployeeId { get; set; }
        public string PaymentTypeId { get; set; }
        public string DebitCardId { get; set; }
        public string VirtualAccountId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string TransactionType { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual DebitCard DebitCard { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual VirtualAccount VirtualAccount { get; set; }
    }
}
