//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPA_Desktop_NT20_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction : ObservableObject
    {
        private string transactionId;
        private DateTime transactionDate;
        private int amount;
        private string transactionType;


        public Transaction(string transactionId, DateTime transactionDate, int amount, string transactionType)
        {
            this.transactionId = transactionId;
            this.transactionDate = transactionDate;
            this.amount = amount;
            this.transactionType = transactionType; 
        }

        public string TransactionId
        {
            get { return transactionId; }
            set { transactionId = value; OnPropertyChanged("TransactionId");  }
        }


        public DateTime TransactionDate
        {
            get { return transactionDate; }
            set { transactionDate = value; OnPropertyChanged("TransactionDate"); }
        }


        public int Amount
        {
            get { return amount; }
            set { amount = value; OnPropertyChanged("Amount");  }
        }


        public string TransactionType
        {
            get { return transactionType; }
            set { transactionType = value; OnPropertyChanged("TransactionType");  }
        }


        public virtual Account Account { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
